use `push-by-digest=true` and capture the remote hash from the buildx build output

diff --git a/.github/actions/build-linux-image/action.yml b/.github/actions/build-linux-image/action.yml
--- a/.github/actions/build-linux-image/action.yml
+++ b/.github/actions/build-linux-image/action.yml
@@ -6,7 +6,14 @@ inputs:
   tag: {type: string, required: true, description: Image tag}
   arch: {type: string, required: true, description: Image arch}
   repo: {type: string, required: true, description: Image repo}
+  push: {type: string, required: true, description: Whether to push the image}
   retries: {type: string, default: '10', description: Number of times to retry the container build}
+
+outputs:
+  hash_amd64:
+    value: "${{ steps.build.outputs.hash_amd64 }}"
+  hash_arm64:
+    value: "${{ steps.build.outputs.hash_arm64 }}"
 
 runs:
   using: composite
@@ -26,23 +33,42 @@ runs:
       shell: bash
       env:
         NODE_NO_WARNINGS: 1
-        repo: ${{ inputs.repo }}
+        arch: "${{ inputs.arch }}"
+        push: "${{ inputs.push }}"
+        repo: "${{ inputs.repo }}"
+        retries: "${{ inputs.retries }}"
+        tag: "${{ inputs.tag }}"
       run: |
-        i=0
+        set -euo pipefail;
+
+        declare i=0;
+        declare -a outputs=();
+
+        if test "${push}" = true; then
+          outputs+=(--output "type=image,compression=zstd,force-compression=true,oci-mediatypes=true,push=true,push-by-digest=true,name=${repo}");
+        fi
+
         until devcontainer build \
-          --platform "linux/${{ inputs.arch }}" \
-          --cache-from "${repo,,}:${{ inputs.tag }}" \
-          --image-name "${repo,,}:${{ inputs.tag }}" \
+          --platform "linux/${arch}" \
+          --cache-from "${repo,,}:${tag}" \
+          --image-name "${repo,,}:${tag}" \
           --workspace-folder "$(realpath -m ./image)" \
-          --output "type=docker,compression=zstd,force-compression=true,dest=${{ runner.temp }}/${{ inputs.arch }}.tar.zst,oci-mediatypes=true"
+          "${outputs[@]}" 2>&1 \
+        | tee "${{ runner.temp }}/${arch}.log" 1>&2
         do
-          if test "${i}" -lt ${{inputs.retries}}; then
+          if test "${i}" -lt "${retries}"; then
             j=$((i++));
             t=$((i * i * 5));
             echo "Attempt $j failed! Trying again in $t seconds...";
             sleep $t;
           else
-            echo "Failed to build ${{ inputs.repo }}:${{ inputs.tag }}-${{ inputs.arch }}";
+            echo "Failed to build ${repo,,}:${tag}";
             exit 1;
           fi
         done
+
+        if test "${push}" = true; then
+          echo "hash_${arch}=$(grep 'exporting manifest sha256:' "${{ runner.temp }}/${arch}.log" | tail -n1 | cut -d' ' -f4)" >> "$GITHUB_OUTPUT";
+        else
+          echo "hash_${arch}=" >> "$GITHUB_OUTPUT";
+        fi
