add `RAPIDS_VERSION` envvar to containers (#317)

diff --git a/.github/workflows/build-test-and-push-linux-image.yml b/.github/workflows/build-test-and-push-linux-image.yml
--- a/.github/workflows/build-test-and-push-linux-image.yml
+++ b/.github/workflows/build-test-and-push-linux-image.yml
@@ -54,8 +54,8 @@ jobs:
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
-          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
+          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER || vars.DOCKERHUB_USER }}
+          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}
 
       - name: Build ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
         uses: ./.github/actions/build-linux-image
@@ -73,27 +73,11 @@ jobs:
           name: ${{ steps.json.outputs.tag }}-${{ matrix.arch }}
           path: ${{ runner.temp }}/${{ matrix.arch }}.tar
 
-  merge-artifacts:
-    if: inputs.push == 'true'
-    name: Download
-    needs: build-test-and-upload
-    runs-on: ubuntu-latest
-    steps:
-      - name: Merge image artifacts
-        uses: actions/upload-artifact/merge@v4
-        with:
-          retention-days: 1
-          delete-merged: true
-          compression-level: 0
-          name: ${{ needs.build-test-and-upload.outputs.tag }}
-          pattern: ${{ needs.build-test-and-upload.outputs.tag }}-*
-
   push-to-dockerhub:
     if: inputs.push == 'true'
     name: Push to Docker Hub
     needs:
       - build-test-and-upload
-      - merge-artifacts
     runs-on: ubuntu-latest
     steps:
       - name: Checkout ${{ github.repository }}
@@ -109,33 +93,41 @@ jobs:
       - name: Download ${{ needs.build-test-and-upload.outputs.tag }}
         uses: actions/download-artifact@v4
         with:
-          name: ${{ needs.build-test-and-upload.outputs.tag }}
+          pattern: ${{ needs.build-test-and-upload.outputs.tag }}-*
           path: ${{ runner.temp }}
+          merge-multiple: true
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
-          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
-          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
+          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER || vars.DOCKERHUB_USER }}
+          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN || secrets.DOCKERHUB_TOKEN }}
 
       - name: Push multiarch manifest to Docker Hub
         shell: bash --noprofile --norc -x -eo pipefail {0}
         env:
+          os: "${{ inputs.os }}"
           name: "${{ inputs.repo }}:${{ needs.build-test-and-upload.outputs.tag }}"
         run: |
-
+          # List downloaded artifacts
           find "${{ runner.temp }}/" -type f -name '*.tar';
-
-          docker manifest rm ${name,,} || true;
-
+          # Ensure name is lowercase
+          name="${name,,}";
           hashes=();
-
           for arch in "amd64" "arm64"; do
             # Load the arch-specific image with the final name
             docker load --input "${{ runner.temp }}/${arch}.tar";
             # Push the local image to the registry and save the remote hash
-            hashes+=("$(docker push ${name,,} | tail -n1 | cut -d' ' -f3)");
+            hashes+=("$(docker push "${name}" | tee >(cat -) 1>&2 | tail -n1 | cut -d' ' -f3)");
+            # Clean up after pushing so we don't run out of disk space
+            rm -f "${{ runner.temp }}/${arch}.tar";
+            docker manifest rm "${name}" || true;
+            docker image rm -f "${name}" || true;
+            docker system prune -f;
           done
-
+          sleep 5;
           # Create and push the multiarch manifest
-          docker buildx imagetools create --tag ${name,,} ${hashes[@]};
+          docker buildx imagetools create --tag "${name}" "${hashes[@]}";
+          sleep 5;
+          # Create and push the multiarch manifest without the OS in the tag
+          docker buildx imagetools create --tag "${name/%-${os//:/}}" "${hashes[@]}";
