restart sccache to apply new configuration (#658)

diff --git a/.github/workflows/test-rapids-build-times.yml b/.github/workflows/test-rapids-build-times.yml
--- a/.github/workflows/test-rapids-build-times.yml
+++ b/.github/workflows/test-rapids-build-times.yml
@@ -69,6 +69,7 @@ jobs:
         SCCACHE_DIST_MAX_RETRIES=inf
         SCCACHE_DIST_FALLBACK_TO_LOCAL_COMPILE=false
         SCCACHE_DIST_AUTH_TOKEN_VAR=RAPIDS_AUX_SECRET_1
+        TIME=real:\t%E
         ${{ matrix.env }}
       build_command: |
         function begin_group() {
@@ -99,7 +100,7 @@ jobs:
           begin_group "$group";
 
           echo "Working directory: $(pwd)";
-          echo "Running command: ${command[*]}";
+          echo "Running command: ${command[*]@Q}";
           "${command[@]}" || exit_code=$?;
 
           end_group "$group" "$exit_code"
@@ -107,16 +108,46 @@ jobs:
           return "$exit_code"
         }
 
-        # Clone all the repos
-        run_command "Clone RAPIDS repositories" \
-          clone-all -j$(nproc) -b ${{ inputs.branch }} -v -q --clone-upstream --depth 1 --single-branch --shallow-submodules --no-update-env;
+        # convert ucx branch names
+        convert_ucx_branch() {
+          local -;
+          set -euo pipefail;
 
-        run_command "Create RAPIDS python environment" \
-          rapids-post-start-command;
+          local repo="$1"
+          local custom_branch="$2"
+          local normalized_branch="${custom_branch}"
+
+          if [[ "${repo}" == "ucx"* ]]; then
+              # Only convert branches that match the pattern release/YY.MM
+              if [[ "${custom_branch}" =~ ^release/[0-9]{2}\.[0-9]{2}$ ]]; then
+                  RAPIDS_VERSION=$(echo "${custom_branch}" | awk '{split($0, a, "/"); print a[2]}')
+                  # Get UCX version associated w/ RAPIDS version
+                  UCX_VERSION="$(curl -sL https://version.gpuci.io/rapids/${RAPIDS_VERSION})"
+                  normalized_branch="release/${UCX_VERSION}"
+              fi
+          fi
+
+          echo "${normalized_branch}"
+        }
+
+        # Clone all the repos
+        time run_command "Clone RAPIDS repositories" bash -c "\
+          RAPIDS_TO_UCXX_BRANCH=\"$(convert_ucx_branch ucxx '${{ inputs.branch }}')\";
+          CLONE_ARGS=(-j$(nproc) -q -v --clone-upstream --depth 1 --single-branch --shallow-submodules --no-update-env);
+          clone-all  -b \"${{ inputs.branch }}\"    \${CLONE_ARGS[*]} >/dev/null 2>&1;
+          clone-ucxx -b \"\$RAPIDS_TO_UCXX_BRANCH\" \${CLONE_ARGS[*]} >/dev/null 2>&1;
+        " 2>&1
+
+        sleep 1
+
+        time run_command "Create RAPIDS python environment" bash -c "\
+          rapids-post-start-command >/dev/null" 2>&1
+
+        sleep 1
 
         # Configure all the C++ libs
-        run_command "Configure C++ libraries" bash -c "\
-          time configure-all \
+        time run_command "Configure C++ libraries" bash -c "\
+          configure-all \
             -j${PARALLEL_LEVEL} \
             -GNinja \
             -Wno-dev \
@@ -125,15 +156,24 @@ jobs:
             -DBUILD_PRIMS_BENCH=ON \
             -DBUILD_SHARED_LIBS=ON \
             -DRAFT_COMPILE_LIBRARY=ON \
-            -DBUILD_CUGRAPH_MG_TESTS=ON"
+            -DBUILD_CUGRAPH_MG_TESTS=ON \
+          >/dev/null" 2>&1
+
+        sleep 1
 
         for ENVVAR in "SCCACHE_RECACHE=1" \
                       "SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE=0" \
                       "SCCACHE_S3_USE_PREPROCESSOR_CACHE_MODE=1" ; do
 
+          # Restart sccache
+          run_command "Start sccache (${ENVVAR})" bash -c "\
+            ${ENVVAR} devcontainer-utils-start-sccache --kill-all >/dev/null 2>&1"
+
           # Build all the C++ libs
-          run_command "Build C++ libraries (${ENVVAR})" bash -c "
-            time ${ENVVAR} build-all-cpp -j${PARALLEL_LEVEL}"
+          time run_command "Build C++ libraries (${ENVVAR})" bash -c "\
+            ${ENVVAR} build-all-cpp -j${PARALLEL_LEVEL} >/dev/null" 2>&1
+
+          sleep 1
 
           # Print cache and dist stats
           run_command "sccache stats (${ENVVAR})" \
@@ -142,10 +182,10 @@ jobs:
           # Print build times
           run_command "Build times (${ENVVAR})" bash -c "\
             find /var/log/devcontainer-utils/ -type f -name 'build-*-time.log' -print0 \
-              | xargs -0 -n1 grep -H real | sed 's/real\t/ /g' || :" # Nonfatal if not found
+          | xargs -0 -n1 grep -H real | sed 's/real\t/ /g' || : # Nonfatal if not found"
 
           # Clean
-          sccache -z >/dev/null 2>&1
-          find /var/log/devcontainer-utils/ -type f -name 'build-*-time.log' -delete
-          find ~/ -maxdepth 4 -type l -path '*/cpp/build/latest' -print0 | xargs -P$(nproc) -0 -n1 ninja clean -C
+          run_command "Clean (${ENVVAR})" bash -c "\
+            find /var/log/devcontainer-utils/ -type f -name 'build-*-time.log' -delete >/dev/null 2>&1 || : # Nonfatal if not found
+            find ~/ -maxdepth 4 -type l -path '*/cpp/build/latest' -print0 | xargs -P$(nproc) -0 -n1 ninja clean -C >/dev/null 2>&1 || : # Nonfatal if not found"
         done
